updated configs

diff --git a/configs/zshrc b/configs/zshrc
--- a/configs/zshrc
+++ b/configs/zshrc
@@ -1,5 +1,5 @@
 # If you come from bash you might have to change your $PATH.
-# export PATH=$HOME/bin:/usr/local/bin:$PATH
+#export PATH=$PATH:$HOME/bin:/usr/local/bin
 
 # Path to your oh-my-zsh installation.
 export ZSH="$HOME/.oh-my-zsh"
@@ -48,7 +48,7 @@ ZSH_THEME=`cat ~/.zshtheme`
 # ENABLE_CORRECTION="true"
 
 # Uncomment the following line to display red dots whilst waiting for completion.
-# COMPLETION_WAITING_DOTS="true"
+ COMPLETION_WAITING_DOTS="true"
 
 # Uncomment the following line if you want to disable marking untracked files
 # under VCS as dirty. This makes repository status check for large repositories
@@ -67,7 +67,7 @@ ZSH_THEME=`cat ~/.zshtheme`
 # Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
 # Example format: plugins=(rails git textmate ruby lighthouse)
 # Add wisely, as too many plugins slow down shell startup.
-plugins=(git emacs python rsync sudo tmux)
+plugins=(git emacs python rsync sudo tmux command-not-found wd docker)
 
 source $ZSH/oh-my-zsh.sh
 
@@ -105,13 +105,117 @@ alias "c=xclip"
 alias "v=xclip -o"
 alias "cs=xclip -selection clipboard"
 alias "vs=xclip -o -selection clipboard"
-alias "emacsnw=emacsclient -nw"
-alias "enw=emacsnw"
+#https://stackoverflow.com/questions/10190358/how-to-use-emacsclient-on-root-files-using-sudo-and-a-single-daemon#10191436
+alias "e=emacsclient -t -a=" #emacs
+alias "se=SUDO_EDITOR='emacsclient -t -a=' sudoedit" #sudo emacs
+alias "ew=emacsclient -c --no-wait -a=" #emacs window
+alias "sew=SUDO_EDITOR='emacsclient -c -a=' sudoedit" #sudo emacs window
 alias "wcl=wc -l"
-alias "n=nemo . &"
+alias "t=tmux attach || tmux"
+alias "tdt=tmux detach"
+#alias "n=nemo . &"
+alias "sopen=gksu xdg-open"
+alias sudo='sudo '
+
+#alias apt='sudo apt'
+#alias ins='sudo apt install'
+#alias rem='sudo apt autoremove --purge'
+#alias upd='sudo apt update;apt list --upgradeable'
+#alias upg='sudo apt upgrade;cat /var/run/reboot-required||echo "no restart needed :)"'
+#alias dupg='sudo apt dist-upgrade;cat /var/run/reboot-required||echo "no restart needed :)"'
+
+alias "pacman=sudo pacman"
+alias "ins=sudo pacman -Sy"
+alias "rem=sudo pacman -Rdd"
+alias "upd=sudo pacman -Syy"
+alias "upg=sudo pacman -Syu"
+
+#alias "ins=aurman -S"
+#alias "rem=aurman -R"
+
+#alias "dnf=sudo dnf"
+#alias "ins=sudo dnf install"
+#alias "rem=sudo dnf remove"
+#alias "upd=sudo dnf check-update"
+#alias "upg=sudo dnf upgrade"
+
+#ins(){
+#    PACMAN_LIST=
+#    AUR_LIST=
+#    for item in $@
+#    do
+#	echo -n "Looking up $item... "
+#	if pkgfile "$item" > /dev/null; then
+#	    PACMAN_LIST="$PACMAN_LIST $item"
+#	    echo "found in official repos"
+#	else
+#	    AUR_LIST="$AUR_LIST $item"
+#	    echo "not found in official repos, will try AUR later"
+#	fi
+#    done
+#    echo "pacman:$PACMAN_LIST"
+#    echo "aurman:$AUR_LIST"
+#    if [[ ! -z "$PACMAN_LIST" ]]; then
+#	echo sudo pacman -Sy $PACMAN_LIST
+#	sudo pacman -Sy `echo $PACMAN_LIST`
+#    fi
+#    if [[ ! -z "$AUR_LIST" ]]; then
+#	echo aurman -S $AUR_LIST
+#	aurman -S `echo $AUR_LIST`
+#    fi
+#}
+
+i(){
+    cols=`tput cols`
+    if [[ $# -eq 0 ]]; then
+	      i .
+    fi
+    while [[ $# -ne 0 ]]; do
+        printf '=%.0s' {1..$cols}
+        if [[ -f "$1" ]]; then
+            cat "$1"
+        else
+            l "$1"
+        fi
+        printf '-%.0s' {1..$cols}
+        l -d "$1"
+        shift
+    done
+}
+
+open(){
+    xdg-open $@ &
+}
+
+f(){
+    fm=nautilus
+    #fm=nemo
+    if [[ $# == 0 ]]
+    then
+        $fm . &
+    else
+        $fm $@ &
+    fi
+}
+
+#wind = find | wc -l
+wind(){
+    find $@ | wc -l
+}
+
+
+#key bindings
+bindkey '^H' backward-kill-word
+bindkey -M emacs '^[[3;5~' kill-word
+
+#autocomplete
+setopt completealiases
+
+#The program 'xyz' is not currently installed. You can install it by typing...
+#. /etc/zsh_command_not_found
 
 #start in custom directory
-if [[ `pwd` == "$HOME" ]]
-then
-    cd /DATA/
-fi
+#if [[ `pwd` == "$HOME" ]]
+#then
+#    cd /DATA/
+#fi
